version: '3.2'

services:
   db:
     image: mysql
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: yes
       MYSQL_DATABASE: mediawiki
       MYSQL_USER: mediawiki
       MYSQL_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MEDIAWIKI_VERSION: 1.27.4
    ports:
      - 80:80

    links:
      - db
    depends_on:
      - db
    # uncomment the 'volumes' section to retain uploads
    # volumes:
    #   - /local/data/dir:/data:rw
    environment:
      MEDIAWIKI_SITE_SERVER: //my-wiki
      MEDIAWIKI_SITE_NAME: My Awesome Wiki

      # you need to specify the reference to the database, Docker no longer
      # shares environmental variables between linked containers
      MEDIAWIKI_DB_TYPE: mysql # 'mysql' or 'postgres'
      MEDIAWIKI_DB_HOST: db
      MEDIAWIKI_DB_USER: mediawiki
      MEDIAWIKI_DB_PASSWORD: password
      MEDIAWIKI_DB_NAME: mediawiki
      # MEDIAWIKI_ENABLE_SSL: true
