---

- include_tasks: linux.yml

- name: get binaries
  get_url: url="{{ item.url }}" dest="{{ item.dest }}"
  with_items:
    - url: https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube-linux-amd64
      dest: "{{ minikube_install_dir }}/minikube"
    - url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
      dest: "{{ minikube_install_dir }}/kubectl"
    - url: "https://github.com/docker/machine/releases/download/{{ docker_machine_version }}/docker-machine-Linux-x86_64"
      dest: "{{ minikube_install_dir }}/docker-machine"

- name: chmod binaries
  file: dest="{{ minikube_install_dir }}/{{ item }}" mode=0755
  with_items:
    - minikube
    - kubectl
    - docker-machine
